import 'reset-css'

import './main.scss'
import './src/components/typography/typography'
import './src/components/grid/grid'
import './src/components/app-header/app-header'
import './src/components/base-btn/base-btn'
import './src/components/main-info/main-info'
import './src/components/second-page/second-page'
import './src/components/animate-btn/animate-btn'
import './src/components/third-page/third-page'
import './src/components/fourth-page/fourth-page'
import './src/components/fifth-page/fifth-page'
import './src/components/six-page/six-page'
import './src/components/footer/footer'
import './src/components/modal-window/modal-window'